# Generated by Django 4.2.11 on 2026-04-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para contabilizar compras de este producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='contabilidad.plancuentas'),
        ),
    ]
