# Generated by Django 4.2.11 on 2026-04-05 08:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0003_alter_registropago_empresa'),
        ('empresas', '0001_initial'),
        ('compras', '0002_alter_compradetalle_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_asiento', models.CharField(db_index=True, help_text='Número correlativo del asiento', max_length=50)),
                ('tipo_asiento', models.CharField(db_index=True, help_text='Tipo de asiento (COMPRA, VENTA, AJUSTE, etc)', max_length=50)),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.TextField()),
                ('moneda', models.CharField(choices=[('PYG', 'Guaraní'), ('USD', 'Dólar')], db_index=True, default='PYG', max_length=3)),
                ('total_debe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_haber', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('registrado', 'Registrado'), ('reversado', 'Reversado')], db_index=True, default='borrador', max_length=20)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compra', models.OneToOneField(blank=True, help_text='Compra que generó este asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asiento_contable', to='compras.compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario_crea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, help_text='Venta que generó este asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asiento_contable', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero_asiento'],
            },
        ),
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(db_index=True, help_text='Código completo de la cuenta (ej: 1410, 2110)', max_length=20)),
                ('codigo_reducido', models.CharField(blank=True, help_text='Código reducido para reportes', max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('condicion', models.CharField(choices=[('deudora', 'Cuenta Deudora'), ('acreedora', 'Cuenta Acreedora')], help_text='Naturaleza de la cuenta (deudora o acreedora)', max_length=10)),
                ('clase', models.CharField(choices=[('sintetica', '1 - Sintética (Agrupadora)'), ('analitica', '2 - Analítica (Detalle)')], default='analitica', help_text='Tipo de cuenta: sintética (agrupa) o analítica (detalle)', max_length=10)),
                ('acepta_item', models.BooleanField(default=False, help_text='Permite asignar ítems contables (P||RUC)')),
                ('acepta_centro_costo', models.BooleanField(default=False, help_text='Permite asignar centro de costo')),
                ('acepta_nivel', models.BooleanField(default=False, help_text='Permite asignar nivel (clvl)')),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('parent', models.ForeignKey(blank=True, help_text='Cuenta padre (para cuentas sintéticas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.plancuentas')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacion', models.CharField(blank=True, help_text='Observación de línea (ej: P800190432 para item contable)', max_length=255)),
                ('item_contable', models.CharField(blank=True, help_text='Ítem contable (P + RUC o código único)', max_length=50)),
                ('centro_costo', models.CharField(blank=True, help_text='Centro de costo', max_length=50)),
                ('nivel', models.CharField(blank=True, help_text='Nivel', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asiento')),
                ('compra_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_asiento', to='compras.compradetalle')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_asiento', to='contabilidad.plancuentas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
                'ordering': ['asiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True)),
                ('moneda_origen', models.CharField(default='USD', help_text='Moneda a convertir (ej: USD)', max_length=3)),
                ('moneda_destino', models.CharField(default='PYG', help_text='Moneda destino (ej: PYG)', max_length=3)),
                ('tasa', models.DecimalField(decimal_places=6, help_text='Tasa de cambio (ej: 5200.00 PYG por 1 USD)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_diarias', to='empresas.empresa')),
                ('usuario_carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_cargadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización Diaria',
                'verbose_name_plural': 'Cotizaciones Diarias',
                'ordering': ['-fecha', 'moneda_origen', 'moneda_destino'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCuenta',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('movimiento_debe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('movimiento_haber', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='contabilidad.plancuentas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Saldo de Cuenta',
                'verbose_name_plural': 'Saldos de Cuentas',
                'ordering': ['cuenta', '-fecha'],
                'unique_together': {('empresa', 'cuenta', 'fecha')},
            },
        ),
        migrations.AddIndex(
            model_name='plancuentas',
            index=models.Index(fields=['empresa', 'codigo_cuenta'], name='contabilida_empresa_957dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='plancuentas',
            index=models.Index(fields=['empresa', 'activa'], name='contabilida_empresa_28797c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plancuentas',
            unique_together={('empresa', 'codigo_cuenta')},
        ),
        migrations.AddIndex(
            model_name='lineaasiento',
            index=models.Index(fields=['asiento', 'cuenta'], name='contabilida_asiento_5f50ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotizaciondiaria',
            unique_together={('empresa', 'fecha', 'moneda_origen', 'moneda_destino')},
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['empresa', 'tipo_asiento', 'fecha'], name='contabilida_empresa_aee177_idx'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_f123b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('empresa', 'numero_asiento')},
        ),
    ]
