# Generated by Django 4.2.11 on 2026-04-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compradetalle_impuesto_porcentaje'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='gasto',
            field=models.ForeignKey(blank=True, help_text='Gasto que generó este asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='compras.gasto'),
        ),
    ]
