# Generated by Django 4.2.11 on 2026-04-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('email_cliente', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono_cliente', models.CharField(blank=True, default='', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('notas', models.TextField(blank=True, default='')),
                ('condiciones_pago', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.presupuesto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalles de Presupuesto',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['empresa', 'estado'], name='presupuesto_empresa_50ab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['empresa', 'cliente'], name='presupuesto_empresa_085771_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['empresa', 'fecha_creacion'], name='presupuesto_empresa_1e3d97_idx'),
        ),
    ]
