# Generated by Django 4.2.11 on 2026-04-02 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ruc', models.CharField(blank=True, default='', max_length=30)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion_facturacion', models.TextField(blank=True, default='')),
                ('direccion_entrega', models.TextField(blank=True, default='')),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona Física'), ('empresa', 'Empresa')], default='persona', max_length=20)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('zona', models.CharField(blank=True, default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'ruc')},
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(default='Principal', max_length=50)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('departamento', models.CharField(blank=True, default='', max_length=100)),
                ('pais', models.CharField(default='Paraguay', max_length=50)),
                ('es_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('es_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
