# Generated by Django 4.2.11 on 2026-04-02 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ruc', models.CharField(blank=True, default='', max_length=30)),
                ('razon_social', models.CharField(blank=True, default='', max_length=255)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('moneda_principal', models.CharField(choices=[('PYG', 'Guaraní'), ('USD', 'Dólar')], default='PYG', max_length=3)),
                ('activa', models.BooleanField(default=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
