# Generated by Django 4.2.11 on 2026-04-04 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        ('empresas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Número de factura del proveedor', max_length=50)),
                ('fecha', models.DateField(db_index=True)),
                ('moneda', models.CharField(choices=[('PYG', 'Paraguayo'), ('USD', 'Dólar')], default='PYG', max_length=3)),
                ('cotizacion_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Cotización USD - OBLIGATORIA si moneda es USD', max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuestos_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Recepción'), ('recepcionada', 'Recepcionada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('almacen', models.ForeignKey(help_text='Almacén destino para productos', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('ruc_numero', models.CharField(db_index=True, max_length=50)),
                ('pais', models.CharField(help_text='País de origen del proveedor - REQUERIDO', max_length=100)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contacto_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('importancia', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=20)),
                ('dias_credito', models.IntegerField(default=0, help_text='Días de plazo de crédito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'ruc_numero')},
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_servicio', models.BooleanField(default=False)),
                ('descripcion', models.CharField(help_text='Descripción del producto/servicio comprado', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('categoria_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.categoriagasto')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_detalles', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'ordering': ['compra', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_set', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_recepcionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario_registra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('PYG', 'Paraguayo'), ('USD', 'Dólar')], default='PYG', max_length=3)),
                ('comprobante', models.CharField(blank=True, default='', max_length=50)),
                ('aprobado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, default='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.categoriagasto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', 'fecha', 'categoria'], name='compras_gas_empresa_c98725_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'estado', 'fecha'], name='compras_com_empresa_2f7e45_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'proveedor', 'fecha'], name='compras_com_empresa_b8b54b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('empresa', 'numero', 'proveedor')},
        ),
    ]
