# Generated by Django 4.2.11 on 2026-04-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('compras', '0002_alter_compradetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable obligatoria para asientos de compra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_set',
            field=models.EmailField(blank=True, default='', help_text='Email SET (Sistema Electrónico de Tributación)', max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emite_electronica',
            field=models.BooleanField(default=False, help_text='Si el proveedor emite factura electrónica'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc_alfanumerico',
            field=models.CharField(blank=True, default='', help_text='RUC alfanumérico para facturas de extranjeros (ej: EXT-12345)', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='timbrado_numero',
            field=models.CharField(blank=True, default='', help_text='Número de timbrado para factura', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='timbrado_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del timbrado (no aplica si es electrónico)', null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email general', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc_numero',
            field=models.CharField(db_index=True, help_text='RUC numérico', max_length=50),
        ),
    ]
