# Generated by Django 4.2.11 on 2026-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_add_condicion_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
