# Generated by Django 4.2.11 on 2026-04-02 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('tipo', models.CharField(choices=[('clientes', 'Clientes'), ('productos', 'Productos'), ('stock', 'Stock'), ('ventas', 'Ventas'), ('mixto', 'Mixto (múltiples hojas)')], max_length=20)),
                ('estado', models.CharField(choices=[('subido', 'Archivo Subido'), ('validando', 'Validando'), ('validado', 'Validación Completa'), ('importando', 'Importando'), ('completado', 'Completado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='subido', max_length=20)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_validas', models.IntegerField(default=0)),
                ('filas_warnings', models.IntegerField(default=0)),
                ('filas_errores', models.IntegerField(default=0)),
                ('filas_importadas', models.IntegerField(default=0)),
                ('reporte_validacion', models.JSONField(blank=True, null=True)),
                ('reporte_errores', models.JSONField(blank=True, null=True)),
                ('archivo_errores', models.FileField(blank=True, null=True, upload_to='importaciones/errores/')),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Trabajo de Importación',
                'verbose_name_plural': 'Trabajos de Importación',
                'ordering': ['-created_at'],
            },
        ),
    ]
