# Generated by Django 4.2.11 on 2026-04-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('contador', 'Contador')], default='vendedor', help_text='Rol dentro de su empresa', max_length=20),
        ),
    ]
