# Generated by Django 4.2.11 on 2026-04-05 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0002_usuario_empresa_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcceso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('contador', 'Contador')], max_length=20)),
                ('modulos_permitidos', models.JSONField(default=list, help_text='Lista de módulos permitidos para este rol')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_accesos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Acceso',
                'verbose_name_plural': 'Configuraciones de Acceso',
                'unique_together': {('empresa', 'rol')},
            },
        ),
    ]
