# Generated by Django 4.2.11 on 2026-04-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('compras', '0005_alter_compradetalle_impuesto_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('IT', 'IT / Tecnología'), ('planta', 'Planta / Maquinaria'), ('mobiliario', 'Mobiliario'), ('vehiculo', 'Vehículo'), ('edificio', 'Edificio'), ('terreno', 'Terreno'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, help_text='Valor estimado al final de la vida útil', max_digits=15)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_activacion', models.DateField(blank=True, help_text='Fecha en la que el activo comenzó a depreciarse', null=True)),
                ('vida_util_anios', models.PositiveIntegerField(default=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=20)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('numero_factura', models.CharField(blank=True, default='', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos_fijos/')),
                ('notas', models.TextField(blank=True, default='')),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_libro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionActivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planta', models.CharField(max_length=100)),
                ('edificio', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['planta', 'edificio', 'area'],
                'unique_together': {('empresa', 'planta', 'edificio', 'area')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, default='')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='activos_fijos.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entregados', to=settings.AUTH_USER_MODEL)),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='activos_fijos.ubicacionactivo')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='activos_fijos.ubicacionactivo')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_activo_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Activo',
                'verbose_name_plural': 'Movimientos de Activos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoActivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=15)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=15)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proveedor_servicio', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos_fijos.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento de Activo',
                'verbose_name_plural': 'Mantenimientos de Activos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionActivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('vida_util_default', models.PositiveIntegerField(default=5, help_text='Vida útil por defecto en años para esta clasificación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Clasificación de Activo',
                'verbose_name_plural': 'Clasificaciones de Activos',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='BajaActivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_baja', models.DateField()),
                ('motivo', models.CharField(choices=[('obsolescencia', 'Obsolescencia'), ('daño_irreparable', 'Daño Irreparable'), ('venta', 'Venta'), ('donacion', 'Donación'), ('robo', 'Robo/Pérdida'), ('otro', 'Otro')], default='obsolescencia', max_length=20)),
                ('motivo_detalle', models.TextField(blank=True, default='')),
                ('valor_rescate', models.DecimalField(decimal_places=2, default=0, help_text='Valor obtenido por venta o rescate', max_digits=15)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja', to='activos_fijos.activofijo')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baja de Activo',
                'verbose_name_plural': 'Bajas de Activos',
                'ordering': ['-fecha_baja'],
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos_fijos.centrocosto'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos_fijos.clasificacionactivo'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos_fijos.ubicacionactivo'),
        ),
        migrations.CreateModel(
            name='DepreciacionMensual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_libro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='activos_fijos.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Depreciación Mensual',
                'verbose_name_plural': 'Depreciaciones Mensuales',
                'ordering': ['anio', 'mes'],
                'unique_together': {('empresa', 'activo', 'anio', 'mes')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activofijo',
            unique_together={('empresa', 'codigo')},
        ),
    ]
