# Generated by Django 4.2.11 on 2026-04-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos_fijos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_activo',
            field=models.ForeignKey(blank=True, help_text='Override: Cuenta de Activo Fijo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos_cuenta', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_depreciacion_acumulada',
            field=models.ForeignKey(blank=True, help_text='Override: Cuenta de Depreciación Acumulada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos_dep_acum', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_gasto_depreciacion',
            field=models.ForeignKey(blank=True, help_text='Override: Cuenta de Gasto por Depreciación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos_gasto_dep', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='moneda',
            field=models.CharField(choices=[('PYG', 'Guaraní'), ('USD', 'Dólar')], default='PYG', max_length=3),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='propiedad_terceros',
            field=models.BooleanField(default=False, help_text='Bienes en admisión temporaria/maquila — no deprecian ni van al balance'),
        ),
        migrations.AddField(
            model_name='clasificacionactivo',
            name='cuenta_activo',
            field=models.ForeignKey(blank=True, help_text='Cuenta de Activo Fijo (ej: 1.02.01)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_activo', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='clasificacionactivo',
            name='cuenta_depreciacion_acumulada',
            field=models.ForeignKey(blank=True, help_text='Cuenta de Depreciación Acumulada (ej: 1.02.09)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_dep_acum', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='clasificacionactivo',
            name='cuenta_gasto_depreciacion',
            field=models.ForeignKey(blank=True, help_text='Cuenta de Gasto por Depreciación (ej: 5.01.04)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_gasto_dep', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='clasificacionactivo',
            name='cuenta_resultado_baja',
            field=models.ForeignKey(blank=True, help_text='Cuenta de Resultado por Baja (ej: 4.02.01)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_res_baja', to='contabilidad.plancuentas'),
        ),
        migrations.CreateModel(
            name='ProcesoDepreciacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('error', 'Error')], default='en_proceso', max_length=15)),
                ('activos_procesados', models.PositiveIntegerField(default=0)),
                ('activos_con_error', models.PositiveIntegerField(default=0)),
                ('registros_creados', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('asiento', models.OneToOneField(blank=True, help_text='Asiento contable generado por este proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proceso_depreciacion', to='contabilidad.asiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_depreciacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Depreciación',
                'verbose_name_plural': 'Procesos de Depreciación',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('empresa', 'anio', 'mes')},
            },
        ),
    ]
