# Generated by Django 4.2.11 on 2026-04-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notas', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('facturada', 'Facturada'), ('parcial', 'Pago Parcial'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=50)),
                ('notas', models.TextField(blank=True, default='')),
                ('timbrado', models.CharField(blank=True, default='', max_length=30)),
                ('cdc', models.CharField(blank=True, default='', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cotizacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Línea de Venta',
                'verbose_name_plural': 'Líneas de Venta',
            },
        ),
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_cotizacion', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Línea de Cotización',
                'verbose_name_plural': 'Líneas de Cotización',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('incobrable', 'Incobrable')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
