# Generated by Django 4.2.11 on 2026-04-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('ventas', '0002_registroPago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa'),
        ),
    ]
