# Generated by Django 4.2.11 on 2026-04-02 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('suspendido', 'Suspendido'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('monto_recurrente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('frecuencia_cobro', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('terminos', models.TextField(blank=True, default='')),
                ('notas', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
