# Generated by Django 4.2.11 on 2026-04-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_servicio', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenservicio',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('empresa', 'numero')},
        ),
    ]
